- hosts: localhost
  connection: local
  tasks:
    - name: Yum install epel-release
      action: yum pkg=epel-release state=installed
      when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"

    - name: Install libselinux-python in RH
      action: yum pkg=libselinux-python state=installed
      when: ansible_os_family == "RedHat"

################################################ Configure Ansible  ###################################################

    - name: Create /etc/ansible
      file: path=/etc/ansible state=directory
      
    - name: Set host_key_checking to false in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=host_key_checking value=False

    - name: Set nocolor to 1 in ansible.cfg to avoid strange chars in Ansible outputs
      ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=nocolor value=1

    - name: Set timeout to 30 in ansible.cfg to avoid problems with some VMs
      ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=timeout value=30

    - name: Set transport to ssh in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=transport value=ssh
      when: ansible_os_family == "Debian" or (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 6)  or (ansible_os_family == "Suse" and ansible_distribution_major_version|int >= 10)
      
    - name: Set transport to smart in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=transport value=smart
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version|int < 6) or (ansible_os_family == "Suse" and ansible_distribution_major_version|int < 10)

    - name: Change ssh_args to set ControlPersist to 15 min in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=ssh_connection option=ssh_args value="-o ControlMaster=auto -o ControlPersist=900s"
      when: ansible_os_family == "Debian" or (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7) or (ansible_os_family == "Suse" and ansible_distribution_major_version|int >= 12)
      
    - name: Change ssh_args to remove ControlPersist in REL 6 and older in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=ssh_connection option=ssh_args value=""
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version|int < 7) or (ansible_os_family == "Suse" and ansible_distribution_major_version|int < 12)
      
    - name: Activate SSH pipelining in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=ssh_connection option=pipelining value=True

################################################ Install IM  ###################################################

    - name: Apt-get update
      apt: update_cache=yes cache_valid_time=3600
      when: ansible_os_family == "Debian"

    - name: Apt install requirements Ubuntu/Debian
      apt: name=python-pip,gcc,python-dev,python-pysqlite2,openssh-client,sshpass,libssl-dev,libffi-dev
      when: ansible_os_family == "Debian"

    - name: Apt install requirements Debian
      apt: name=libmariadbd-dev
      when: ansible_distribution == "Debian"

    - name: Apt install requirements Ubuntu
      apt: name=libmysqld-dev
      when: ansible_distribution == "Ubuntu"

    - name: Yum install requirements RH
      yum: name=python-pip,python-distribute,gcc,python-devel,wget,openssh-clients,sshpass,libffi-devel,openssl-devel,mysql-devel,sqlite-devel
      when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"

    - name: Yum install requirements Fedora
      yum: name=python-pip,redhat-rpm-config,gcc,python-devel,wget,openssh-clients,sshpass,libffi-devel,openssl-devel,mysql-devel,sqlite-devel
      when: ansible_distribution == "Fedora"

    - name: Install setuptools with pip
      pip: executable=pip name=setuptools,six extra_args="-I"

    - name: Install last pip version
      easy_install: name=pip state=latest
      ignore_errors: yes

    - name: Install pip libraries
      pip: executable=pip name=pyOpenSSL,MySQL-python,msrest,msrestazure,azure-common,azure-mgmt-storage,azure-mgmt-compute,azure-mgmt-network,azure-mgmt-resource,azure-mgmt-dns
      
    - name: Install IM dependencies for CentOS 6
      pip: name=pysqlite version=2.7.0
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

    - name: Install xmltodict
      pip: executable=pip name=xmltodict

    - name: Install IM
      pip: executable=pip name=IM

    # Pip requests package have a bug in debian systems, remove it and force reinstall python-requests
    - name: Pip uninstall requests Ubuntu/Debian
      pip: executable=pip name=requests state=absent
      when: ansible_os_family == "Debian"

    - name: Apt install requests Ubuntu/Debian
      apt: name=python-requests state=absent
      when: ansible_os_family == "Debian"

    - name: Apt install requests Ubuntu/Debian
      apt: name=python-requests state=present
      when: ansible_os_family == "Debian"
