- hosts: localhost
  connection: local
  vars:
      # Set True to activate IM in single site more (OpenNebula sites)
      SINGLE_SITE: False
      # Hostname of the OpenNebula API server 
      SINGLE_SITE_HOST: onserver.domain.com
      # URL of the IAM TTS server
      TTS_URL: https://localhost:8443
  tasks:
    - name: Yum install epel-release
      action: yum pkg=epel-release state=installed
      when: ansible_os_family == "RedHat"

    - name: Install libselinux-python in RH
      action: yum pkg=libselinux-python state=installed
      when: ansible_os_family == "RedHat"

    - name: Ubuntu 14 install indigo 1 list
      get_url: url=http://repo.indigo-datacloud.eu/repos/1/indigo1-ubuntu14_04.list dest=/etc/apt/sources.list.d/indigo1-ubuntu14_04.list
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"

    - name: Ubuntu 16 install indigo 2 list
      get_url: url=http://repo.indigo-datacloud.eu/repos/2/indigo2-ubuntu16_04.list dest=/etc/apt/sources.list.d/indigo2-ubuntu16_04.list
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16"

    - apt_key: url=http://repo.indigo-datacloud.eu/repository/RPM-GPG-KEY-indigodc state=present
      when: ansible_distribution == "Ubuntu"
      
    - name: Apt-get update
      apt: update_cache=yes
      when: ansible_os_family == "Debian"

    - name: Ubuntu install Ansible with apt
      apt: name=python-im,ansible,python-pip,python-jinja2,sshpass,openssh-client,unzip,python-mysqldb,python-sqlite force=yes
      when: ansible_distribution == "Ubuntu"
      
    - name: RH indigo repos
      get_url: url=http://repo.indigo-datacloud.eu/repos/2/indigo2.repo dest=/etc/yum.repos.d/indigo2.repo
      when: ansible_os_family == "RedHat"

    - rpm_key: state=present key=http://repo.indigo-datacloud.eu/repository/RPM-GPG-KEY-indigodc
      when: ansible_os_family == "RedHat"

    - name: RH7 install Ansible with yum
      yum: name=IM,ansible,python-pip,python-jinja2,sshpass,openssh-clients,unzip,MySQL-python,python-sqlite3dbm
      when: ansible_os_family == "RedHat"

################################################ Configure Ansible  ###################################################

    - name: Create /etc/ansible
      file: path=/etc/ansible state=directory
      
    - name: Set host_key_checking to false in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=host_key_checking value=False

    - name: Set nocolor to 1 in ansible.cfg to avoid strange chars in Ansible outputs
      ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=nocolor value=1

    - name: Set timeout to 30 in ansible.cfg to avoid problems with some VMs
      ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=timeout value=30

    - name: Set transport to ssh in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=transport value=ssh
      when: ansible_os_family == "Debian" or (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 6)  or (ansible_os_family == "Suse" and ansible_distribution_major_version|int >= 10)
      
    - name: Set transport to smart in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=transport value=smart
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version|int < 6) or (ansible_os_family == "Suse" and ansible_distribution_major_version|int < 10)

    - name: Change ssh_args to set ControlPersist to 15 min in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=ssh_connection option=ssh_args value="-o ControlMaster=auto -o ControlPersist=900s"
      when: ansible_os_family == "Debian" or (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7) or (ansible_os_family == "Suse" and ansible_distribution_major_version|int >= 12)
      
    - name: Change ssh_args to remove ControlPersist in REL 6 and older in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=ssh_connection option=ssh_args value=""
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version|int < 7) or (ansible_os_family == "Suse" and ansible_distribution_major_version|int < 12)
      
    - name: Activate SSH pipelining in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=ssh_connection option=pipelining value=True

################################################ Configure IM  ###################################################

    - name: Activate SINGLE_SITE in the IM
      ini_file: dest=/etc/im/im.cfg section=im option=SINGLE_SITE value=True
      when: SINGLE_SITE

    - name: Set SINGLE_SITE_AUTH_HOST in the IM
      ini_file: dest=/etc/im/im.cfg section=im option=SINGLE_SITE_AUTH_HOST value="http://{{SINGLE_SITE_HOST}}:2633"
      when: SINGLE_SITE

    - name: Set SINGLE_SITE_IMAGE_URL_PREFIX in the IM
      ini_file: dest=/etc/im/im.cfg section=im option=SINGLE_SITE_IMAGE_URL_PREFIX value="one://{{SINGLE_SITE_HOST}}/"
      when: SINGLE_SITE

    - name: Set TTS_URL in the IM
      ini_file: dest=/etc/im/im.cfg section=OpenNebula option=TTS_URL value="{{TTS_URL}}"
