---
- hosts: "{{IM_HOST}}"
  become: yes
  become_method: sudo
  gather_facts: false
  vars:
    MICROMAMBA_PATH: /var/tmp/.mamba
    DEFAULT_ANSIBLE_VERSION  : 9.5.1
  tasks:
  ############## To avoid some issues with cloud-init and unattended upgrades ###############
    - name: Avoid unattended upgrades
      raw: |
        sudo touch /var/lib/apt/periodic/upgrade-stamp; \
        sudo touch /var/lib/apt/periodic/update-stamp; \
        sudo touch /var/lib/apt/periodic/download-upgradeable-stamp;
      ignore_errors: yes
      changed_when: false

    - name: Wait for the VM to boot
      raw: systemctl is-system-running --wait
      ignore_errors: yes
      changed_when: false

  ################### Some OSs does not have python by default #########################
    - name: Check Python is installed
      raw: python3 -c 'import sys; print(sys.version_info[1])'
      ignore_errors: yes
      register: python3_version
      changed_when: false

    - name: Bootstrap with python Debian/Ubuntu
      raw: sudo apt update && sudo apt install -y python3.5; sudo apt install -y python3
      ignore_errors: yes
      register: python_install
      changed_when: python_install.stdout_lines|length > 1
      when: python3_version is failed or python3_version.stdout|int < 5

    - name: Bootstrap with python RedHat/CentOS
      raw: sudo yum install -y python3
      ignore_errors: yes
      register: python_install
      changed_when: python_install.stdout_lines|length > 1
      when: python3_version is failed

    - name: Bootstrap with python SUSE
      raw: sudo zypper -n install python3 python3-xml
      ignore_errors: yes
      register: python_install
      changed_when: python_install.stdout_lines|length > 1
      when: python3_version is failed

     # In some cases python link is not created
    - name: Link python 3 or 2 in case is needed
      raw: ls /usr/bin/python || { ls /usr/bin/python3 && ln -s /usr/bin/python3 /usr/bin/python; } || { ls /usr/bin/python2 && ln -s /usr/bin/python2 /usr/bin/python; }
      ignore_errors: yes

    # In case of redhat systems libselinux-python3 is needed
    - name: Install libselinux-python3 on RH systems
      raw: yum -y install libselinux-python3
      ignore_errors: yes

  ################### Some basic OSs operations #########################
    - name: Get Facts
      setup:

    - name: Install EPEL
      command: yum install -y epel-release
      args:
        creates: /etc/yum.repos.d/epel.repo
      when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"

    - name: Fix EPEL
      lineinfile:
        path: /etc/yum.repos.d/epel.repo
        regexp: '^metalink=https:\/\/mirrors\.fedoraproject\.org\/metalink\?repo=epel-\$releasever&arch=\$basearch&infra=\$infra&content=\$contentdir'
        insertafter: '^#baseurl '
        line: 'baseurl=https://dl.fedoraproject.org/pub/archive/epel/8.5.2022-05-10/Everything/x86_64/'
      when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora" and ansible_distribution_major_version|int < 9

    - name: Ensure to Enable EPEL repo
      ini_file:
        dest: /etc/yum.repos.d/epel.repo
        section: epel
        option: enabled
        value: "1"
      when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora" and ansible_distribution_major_version|int < 9
      ignore_errors: yes

    - name: Ubuntu/Debian apt update
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      ignore_errors: yes
      register: apt_update

    - name: Ubuntu/Debian force apt update (avoid apt lock)
      command: apt update
      when: ansible_os_family == "Debian" and apt_update is failed

  ################### Install Ansible/micromamba requisites #########################

    - name: Debian/Ubuntu install requisites with apt
      apt:
        name:
        - wget
        - sshpass
        - openssh-client
        - unzip
        install_recommends: no
      when: ansible_os_family == "Debian"

    - name: Install requisites in RedHat/Suse with yum/zypper
      package:
        name: "{{ requisites_pkgs[ansible_os_family] }}"
        state: present
      vars:
        requisites_pkgs:
          RedHat:
            - wget
            - sshpass
            - openssh-clients
          Suse:
            - wget
            - sshpass
            - openssh
            - unzip
      when: ansible_os_family in requisites_pkgs

  ######################################### Use micromamba to install Ansible #############################################

    - name: Create micromamba directory
      file:
        path: "{{ MICROMAMBA_PATH }}/bin"
        state: directory
        mode: '0755'

    - name: Download micromamba
      command: wget https://github.com/mamba-org/micromamba-releases/releases/latest/download/micromamba-linux-64 -O {{ MICROMAMBA_PATH }}/bin/micromamba
      args:
        creates: "{{ MICROMAMBA_PATH }}/bin/micromamba"

    - name: Make executable
      file:
        path: "{{ MICROMAMBA_PATH }}/bin/micromamba"
        mode: '0755'

    - name: Set Ansible version from playbook var if defined
      set_fact:
        ANSIBLE_VERSION: "{{ im_ansible_version }}"
      when: im_ansible_version is defined and im_ansible_version | length > 0

    - name: Set Ansible version from env if defined
      set_fact: ANSIBLE_VERSION={{ lookup('env','ANSIBLE_VERSION') }}
      when:
        - lookup('env','ANSIBLE_VERSION') != ""
        - ANSIBLE_VERSION is not defined or ANSIBLE_VERSION | length == 0

    - name: Set default ANSIBLE_VERSION
      set_fact:
        ANSIBLE_VERSION: "{{ DEFAULT_ANSIBLE_VERSION }}"
      when: ANSIBLE_VERSION is not defined or ANSIBLE_VERSION | length == 0

    - name: Create base Ansible environment with micromamba
      command: "{{ MICROMAMBA_PATH }}/bin/micromamba create -y -n ansible -r {{ MICROMAMBA_PATH }} python=3.12 paramiko psutil pyyaml jmespath scp pywinrm requests urllib3"
      args:
        creates: "{{ MICROMAMBA_PATH }}/envs/ansible"

    - name: Install requested Ansible version with conda, fallback to pip
      block:
        - name: Install Ansible from conda channel
          command: "{{ MICROMAMBA_PATH }}/bin/micromamba install -y -n ansible -r {{ MICROMAMBA_PATH }} ansible={{ ANSIBLE_VERSION }}"
      rescue:
        - name: Install Ansible from pip as fallback
          command: "{{ MICROMAMBA_PATH }}/bin/micromamba run -n ansible -r {{ MICROMAMBA_PATH }} python -m pip install ansible=={{ ANSIBLE_VERSION }}"

################################################ Configure Ansible  ###################################################

    - name: Create Ansible config file
      copy:
        dest: /var/tmp/ansible.cfg
        content: |
          [defaults]
          transport  = ssh
          timeout = 30
          host_key_checking = False
          nocolor = 1
          become_user = root
          become_method = sudo
          fact_caching = jsonfile
          fact_caching_connection = /var/tmp/facts_cache
          fact_caching_timeout = 86400
          interpreter_python = /usr/bin/python3
          gathering = smart
          roles_path = /var/tmp/ansible/roles
          collections_path = /var/tmp/ansible
          jinja2_extensions = jinja2.ext.do
          allow_world_readable_tmpfiles = True
          ansible_python_interpreter = auto
          [paramiko_connection]
          record_host_keys=False
          [ssh_connection]
          pipelining = True
          ssh_args = -o ControlMaster=auto -o ControlPersist=900s -o UserKnownHostsFile=/dev/null
          [galaxy]
          server_list = galaxy, oldgalaxy
          [galaxy_server.galaxy]
          url = https://galaxy.ansible.com/api/
          [galaxy_server.oldgalaxy]
          url = https://old-galaxy.ansible.com/api/
        mode: '0644'
