---
- hosts: "{{IM_HOST}}"
  become: yes
  become_method: sudo
  gather_facts: false
  vars:
    # Ansible specific Version or "latest"
    ANSIBLE_VERSION: 2.9.13
  tasks:
    - name: Set Ansible version from env if defined
      set_fact: ANSIBLE_VERSION={{ lookup('env','ANSIBLE_VERSION') }}
      when: lookup('env','ANSIBLE_VERSION') != ""

  ################### Some OSs does not have python by default #########################
    - name: Check Python is installed
      raw: python3 -c 'import sys; print(sys.version_info[1])'
      ignore_errors: yes
      register: python3_version
      changed_when: false

    - name: Bootstrap with python Debian/Ubuntu
      raw: sudo apt update && sudo apt install -y python3.5; sudo apt install -y python3
      ignore_errors: yes
      register: python_install
      changed_when: python_install.stdout_lines|length > 1
      when: python3_version is failed or python3_version.stdout|int < 5

    - name: Link correct python version in Ubuntu 14
      raw: ls /usr/bin/python3.5 && sudo rm -f /usr/bin/python3 && sudo ln -s /usr/bin/python3.5 /usr/bin/python3
      when: python3_version is success and python3_version.stdout|int < 5
      ignore_errors: yes

    - name: Bootstrap with python RedHat/CentOS
      raw: sudo yum install -y python3 || { sudo yum install -y epel-release https://repo.ius.io/ius-release-el6.rpm && sudo yum install -y python36 && ln -s /usr/bin/python3.6 /usr/bin/python3; }
      ignore_errors: yes
      register: python_install
      changed_when: python_install.stdout_lines|length > 1
      when: python3_version is failed

    - name: Bootstrap with python SUSE
      raw: sudo zypper -n install python3 python3-xml
      ignore_errors: yes
      register: python_install
      changed_when: python_install.stdout_lines|length > 1
      when: python3_version is failed

     # In some cases python link is not created
    - name: Link python 3 or 2 in case is needed
      raw: ls /usr/bin/python || { ls /usr/bin/python3 && ln -s /usr/bin/python3 /usr/bin/python; } || { ls /usr/bin/python2 && ln -s /usr/bin/python2 /usr/bin/python; }
      become: yes
      ignore_errors: yes

    # In case of redhat systems libselinux-python3 is needed
    - name: Install libselinux-python3 on RH systems
      raw: yum -y install libselinux-python3
      become: yes
      ignore_errors: yes

  ################### Some basic OSs operations #########################
    - name: Get Facts
      setup:

    - name: Install EPEL
      command: yum install -y epel-release
      args:
        creates: /etc/yum.repos.d/epel.repo
      when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"

    - name: Ensure to Enable EPEL repo
      ini_file:
        dest: /etc/yum.repos.d/epel.repo
        section: epel
        option: enabled
        value: 1
      when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"
      ignore_errors: yes

    - name: Ubuntu/Debian apt update
      apt: update_cache=yes
      when: ansible_os_family == "Debian"
      ignore_errors: yes
      register: apt_update

    - name: Ubuntu/Debian force apt update (avoid apt lock)
      command: apt update
      when: ansible_os_family == "Debian" and apt_update is failed

  ################### Install Ansible/pip requisites #########################

    - name: Debian/Ubuntu install requisites with apt
      apt: name=python3-pip,wget,python3-setuptools,sshpass,openssh-client,unzip install_recommends=no
      when: ansible_os_family == "Debian" and not (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int <= 14)

    - name: Ubuntu 14 install requisites with apt
      command: apt install -y --no-install-recommends gcc python3.5-dev libffi-dev libssl-dev python3-pip wget python3-setuptools sshpass openssh-client unzip
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int <= 14

    - name: Ubuntu 14 install pip3.5
      command: python3.5 /usr/lib/python3/dist-packages/easy_install.py "pip>=9.0.3" creates=/usr/local/bin/pip3.5
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int <= 14

    - name: Remove old pip3 in Ubuntu 14
      file: path=/usr/bin/pip3 state=absent
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int <= 14

    - name: Link pip3.5 in Ubuntu 14
      file: src=/usr/local/bin/pip3.5 dest=/usr/bin/pip3 state=link
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int <= 14

    - name: Yum install requisites RH 7/8 or Fedora
      command: yum install -y python3-pip python3-setuptools sshpass openssh-clients
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version|int > 6)

    - name: Yum install requisites RH 6
      command: yum install -y python36-pip python36-setuptools sshpass openssh-clients gcc libffi-devel openssl-devel python36-devel
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 6 

    - name: Link pip3 in RH 6
      command: ln -s /usr/bin/pip3.6 /usr/bin/pip3 creates=/usr/bin/pip3
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 6 

    - name: Zypper install requirements Suse
      zypper: name=python3-pip,python3-setuptools,gcc,python3-devel,wget,libffi-devel,openssl-devel,python3-cryptography,make state=present
      when: ansible_os_family == "Suse"

  ######################################### Use pip to enable to set the version #############################################

    - name: Upgrade pip
      pip:
        name: pip>=9.0.3
        executable: pip3

    - name: Upgrade setuptools with Pip
      pip: name=setuptools state=latest executable=pip3
      when: ansible_os_family != "RedHat" or ansible_distribution_major_version|int > 6

    - name: Install pyOpenSSL
      pip: name=pyOpenSSL state=latest executable=pip3
      when: ansible_os_family != "RedHat" or ansible_distribution_major_version|int > 6

    - name: Ubuntu 14 pip cryptography
      pip: name=cryptography version=2.9.2 executable=pip3
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int <= 14

    - name: Install pkgs with Pip in RH6
      pip: name="{{ item.name }}" version="{{ item.version }}" executable=pip3
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 6
      with_items:
        - { name: 'setuptools', version: '28.8.1' }
        - { name: 'pyyaml', version: '3.13' }
        - { name: 'idna', version: '2.7' }
        - { name: 'argparse', version: '1.4.0' }
        - { name: 'paramiko', version: '2.2.4' }
        - { name: 'xmltodict', version: '0.11.0' }
        - { name: 'cryptography', version: '2.1.0' }
        - { name: 'pyOpenSSL', version: '17.0.0' }

    - name: Install pyyaml
      pip: name=pyyaml executable=pip3

    - name: Install ansible {{ ANSIBLE_VERSION }} with Pip
      pip: name=ansible version={{ ANSIBLE_VERSION }} executable=pip3
      when: ANSIBLE_VERSION != "latest"

    - name: Install latest ansible version with Pip
      pip: name=ansible state=latest executable=pip3
      when: ANSIBLE_VERSION == "latest"

    - name: Ubuntu 14 extra pip packages needed to avoid https issues
      pip: name=urllib3,ndg-httpsclient,pyasn1 executable=pip3
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int <= 14

#################################### Now install scp, jmespath and pywinrm with pip  ##################################

    - name: Install jmespath with Pip
      pip: name=jmespath executable=pip3

    - name: Install cffi with Pip in RH6
      pip: name=cffi executable=pip3
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 6

    - name: Install scp with Pip
      pip: name=scp executable=pip3

    - name: Install pywinrm with Pip
      pip: name=pywinrm executable=pip3
      ignore_errors: yes

################################################ Configure Ansible  ###################################################

    - name: Create /etc/ansible
      file: path=/etc/ansible state=directory

    - name: Create /etc/ansible/ansible.cfg
      file: path=/etc/ansible/ansible.cfg state=touch owner=root group=root mode=0644

    - name: Set Ansible config file values
      ini_file: dest=/etc/ansible/ansible.cfg section={{ item.section }} option={{ item.option }} value="{{ item.value }}"
      with_items:
      - { section: 'defaults', option: 'host_key_checking', value: 'False' }
      - { section: 'defaults', option: 'interpreter_python ', value: '/usr/bin/python3' }
      - { section: 'defaults', option: 'nocolor', value: '1' }
      - { section: 'ssh_connection', option: 'pipelining', value: 'True' }
      - { section: 'defaults', option: 'jinja2_extensions', value: 'jinja2.ext.do' }
      - { section: 'defaults', option: 'allow_world_readable_tmpfiles', value: 'True' }
      - { section: 'defaults', option: 'fact_caching', value: 'jsonfile' }
      - { section: 'defaults', option: 'fact_caching_connection', value: '/var/tmp/facts_cache' }
      - { section: 'defaults', option: 'fact_caching_timeout', value: '86400' }
      - { section: 'defaults', option: 'gathering', value: 'smart' }
      - { section: 'defaults', option: 'roles_path', value: '/etc/ansible/roles' }
      - { section: 'defaults', option: 'timeout', value: '30' }
 
    - name: Set transport to ssh in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=transport value=ssh
      when: ansible_os_family == "Debian" or (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 6)  or (ansible_os_family == "Suse" and ansible_distribution_major_version|int >= 10)

    - name: Set transport to smart in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=transport value=smart
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version|int < 6) or (ansible_os_family == "Suse" and ansible_distribution_major_version|int < 10)

    - name: Change ssh_args to set ControlPersist to 15 min in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=ssh_connection option=ssh_args value="-o ControlMaster=auto -o ControlPersist=900s -o UserKnownHostsFile=/dev/null"
      when: ansible_os_family == "Debian" or (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7) or (ansible_os_family == "Suse" and ansible_distribution_major_version|int >= 12)

    - name: Change ssh_args to remove ControlPersist in REL 6 and older in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=ssh_connection option=ssh_args value="-o UserKnownHostsFile=/dev/null"
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version|int < 7) or (ansible_os_family == "Suse" and ansible_distribution_major_version|int < 12)
