---
- hosts: "{{IM_HOST}}"
  become: yes
  become_method: sudo
  gather_facts: false
  vars:
    # Ansible specific Version or "latest"
    ANSIBLE_VERSION: 2.9.15
  tasks:
    - name: Set Ansible version from env if defined
      set_fact: ANSIBLE_VERSION={{ lookup('env','ANSIBLE_VERSION') }}
      when: lookup('env','ANSIBLE_VERSION') != ""

  ################### Some OSs does not have python by default #########################
    - name: Check Python is installed
      raw: python --version
      ignore_errors: yes
      register: python_exists
      changed_when: false

    - name: Check Python2 or Python3 is installed
      raw: python2 --version || python3 --version
      ignore_errors: yes
      register: python2_exists
      changed_when: false

    - name: Bootstrap with python
      raw: sudo apt update && sudo apt install -y python; sudo yum install -y python || sudo yum install -y python2; sudo zypper -n install python python-xml
      ignore_errors: yes
      register: python_install
      changed_when: python_install.stdout_lines|length > 1
      when: python_exists is failed and python2_exists is failed

     # In some cases python link is not created
    - name: Link python 3 or 2 in case is needed
      raw: ls /usr/bin/python || { ls /usr/bin/python3 && ln -s /usr/bin/python3 /usr/bin/python; } || { ls /usr/bin/python2 && ln -s /usr/bin/python2 /usr/bin/python; }
      become: yes
      ignore_errors: yes

  ################### Some basic OSs operations #########################
    - name: Get Facts
      setup:

    - name: Install EPEL
      command: yum install -y epel-release
      args:
        creates: /etc/yum.repos.d/epel.repo
      when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"

    - name: Ensure to Enable EPEL repo
      ini_file:
        dest: /etc/yum.repos.d/epel.repo
        section: epel
        option: enabled
        value: 1
      when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"
      ignore_errors: yes

    - name: Ubuntu/Debian apt update
      apt: update_cache=yes
      when: ansible_os_family == "Debian"
      ignore_errors: yes
      register: apt_update

    - name: Ubuntu/Debian force apt update (avoid apt lock)
      command: apt update
      when: ansible_os_family == "Debian" and apt_update is failed

  ################### Install Ansible/pip requisites #########################

    - name: Debian/Ubuntu install requisites with apt
      apt: name=wget,python-setuptools,sshpass,openssh-client,unzip install_recommends=no
      when: ansible_os_family == "Debian"

    - name: Debian/Ubuntu install python-pip with apt
      apt: name=python-pip install_recommends=no
      when: ansible_os_family == "Debian" and not (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20)

    - name: Install pip in in Ubuntu 20+
      shell: wget https://bootstrap.pypa.io/get-pip.py && python2 get-pip.py warn=false creates=/usr/local/bin/pip2 chdir=/tmp
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20

    - name: Ubuntu 14 extra packages needed
      apt: name=gcc,python-dev,libffi-dev,libssl-dev install_recommends=no
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int <= 14

    - name: Yum install requisites RH 6/7/ Fedora 27-
      yum: name=python-pip,python-setuptools,sshpass,openssh-clients update_cache=yes
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 6 and ansible_distribution_major_version|int < 8) or (ansible_distribution == "Fedora" and ansible_distribution_major_version|int < 28)

    - name: Yum install requisites RH 8 / Fedora 28+
      command: yum install -y python2-pip python2-setuptools sshpass openssh-clients
      when: (ansible_distribution != "Fedora" and ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8) or (ansible_distribution == "Fedora" and ansible_distribution_major_version|int >= 28)

    - name: Yum install extra requisites RH 6
      yum: name=gcc,libffi-devel,openssl-devel,python-devel update_cache=yes
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 6 

    - name: Zypper install requirements Suse
      zypper: name=python-pip,python-setuptools,gcc,python-devel,wget,libffi-devel,openssl-devel,python-cryptography,make state=present
      when: ansible_os_family == "Suse"

    - name: Apk install requirements Alpine
      package: name=py-setuptools,sshpass,openssh-client,unzip,gcc,libffi-dev,openssl-dev,musl-dev,make,wget,python2-dev
      when: ansible_os_family == "Alpine"

    - name: Apk install pip in Alpine 3.11-
      package: name=py-pip
      when: ansible_os_family == "Alpine" and ansible_distribution_version is version('3.12', '<')

    - name: Apk install pip in Alpine 3.12+
      shell: wget https://bootstrap.pypa.io/get-pip.py && python2 get-pip.py warn=false creates=/usr/local/bin/pip2 chdir=/tmp
      when: ansible_os_family == "Alpine" and ansible_distribution_version is version('3.12', '>=')

    - name: Move original ps in Alpine
      command: mv /bin/ps /sbin/ps creates=/sbin/ps
      when: ansible_os_family == "Alpine"

    - name: Install ps with -p support in Alpine
      get_url:
        url: https://gist.githubusercontent.com/micafer/f74de4dc21a636df30d51202cbeee475/raw/388945406b9e9d225a0c7e95b97fc2515f1a17ef/ps_opt_p_enabled_for_alpine.sh
        dest: /bin/ps
        mode: 0755
        owner: root
        group: root
      when: ansible_os_family == "Alpine"

    - name: Pip install cffi Alpine
      pip: name=wheel
      when: ansible_os_family == "Alpine"

    - name: Install pip and setuptools Py3
      package: name=python3-setuptools,python3-pip
      when: ansible_python.version.major > 2
      ignore_errors: yes

  ######################################### Use pip to enable to set the version #############################################

    - name: Upgrade pip
      pip: name=pip version=9.0.3

    - name: Upgrade setuptools with Pip
      pip: name=setuptools state=latest
      when: ansible_os_family != "RedHat" or ansible_distribution_major_version|int > 6

    - name: Install pyOpenSSL
      pip: name=pyOpenSSL state=latest
      when: ansible_os_family != "RedHat" or ansible_distribution_major_version|int > 6

    - name: Ubuntu 14 pip cryptography
      pip: name=cryptography version=2.9.2
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int <= 14

    - name: Install pkgs with Pip in RH6
      pip: name="{{ item.name }}" version="{{ item.version }}"
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 6
      with_items:
        - { name: 'setuptools', version: '28.8.1' }
        - { name: 'pyyaml', version: '3.13' }
        - { name: 'idna', version: '2.7' }
        - { name: 'argparse', version: '1.4.0' }
        - { name: 'paramiko', version: '2.2.4' }
        - { name: 'xmltodict', version: '0.11.0' }
        - { name: 'cryptography', version: '2.1.0' }
        - { name: 'pyOpenSSL', version: '17.0.0' }

    - name: Install pyyaml
      pip: name=pyyaml

    - name: Install ansible {{ ANSIBLE_VERSION }} with Pip
      pip: name=ansible version={{ ANSIBLE_VERSION }}
      when: ANSIBLE_VERSION != "latest"

    - name: Install latest ansible version with Pip
      pip: name=ansible state=latest
      when: ANSIBLE_VERSION == "latest"

    - name: Ubuntu 14 extra pip packages needed to avoid https issues
      pip: name=urllib3,ndg-httpsclient,pyasn1
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int <= 14

#################################### Now install scp, jmespath and pywinrm with pip  ##################################

    - name: Install jmespath with Pip
      pip: name=jmespath

    - name: Install cffi with Pip in RH6
      pip: name=cffi
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 6

    - name: Install scp with Pip
      pip: name=scp

    - name: Install pywinrm with Pip
      pip: name=pywinrm
      ignore_errors: yes

################################################ Configure Ansible  ###################################################

    - name: Create /etc/ansible
      file: path=/etc/ansible state=directory

    - name: Create /etc/ansible/ansible.cfg
      file: path=/etc/ansible/ansible.cfg state=touch owner=root group=root mode=0644

    - name: Set Ansible config file values
      ini_file: dest=/etc/ansible/ansible.cfg section={{ item.section }} option={{ item.option }} value="{{ item.value }}"
      with_items:
      - { section: 'defaults', option: 'host_key_checking', value: 'False' }
      - { section: 'defaults', option: 'nocolor', value: '1' }
      - { section: 'ssh_connection', option: 'pipelining', value: 'True' }
      - { section: 'defaults', option: 'jinja2_extensions', value: 'jinja2.ext.do' }
      - { section: 'defaults', option: 'allow_world_readable_tmpfiles', value: 'True' }
      - { section: 'defaults', option: 'fact_caching', value: 'jsonfile' }
      - { section: 'defaults', option: 'fact_caching_connection', value: '/var/tmp/facts_cache' }
      - { section: 'defaults', option: 'fact_caching_timeout', value: '86400' }
      - { section: 'defaults', option: 'gathering', value: 'smart' }
      - { section: 'defaults', option: 'roles_path', value: '/etc/ansible/roles' }
      - { section: 'defaults', option: 'timeout', value: '30' }
 
    - name: Set transport to ssh in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=transport value=ssh
      when: ansible_os_family == "Debian" or (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 6)  or (ansible_os_family == "Suse" and ansible_distribution_major_version|int >= 10)

    - name: Set transport to smart in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=transport value=smart
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version|int < 6) or (ansible_os_family == "Suse" and ansible_distribution_major_version|int < 10)

    - name: Change ssh_args to set ControlPersist to 15 min in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=ssh_connection option=ssh_args value="-o ControlMaster=auto -o ControlPersist=900s -o UserKnownHostsFile=/dev/null"
      when: ansible_os_family == "Debian" or (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7) or (ansible_os_family == "Suse" and ansible_distribution_major_version|int >= 12)

    - name: Change ssh_args to remove ControlPersist in REL 6 and older in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=ssh_connection option=ssh_args value="-o UserKnownHostsFile=/dev/null"
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version|int < 7) or (ansible_os_family == "Suse" and ansible_distribution_major_version|int < 12)
