name: SQAaaS IM

on:
  push:
    branches: ["sqa"]

jobs:

  sqaaas_job:
    runs-on: ubuntu-latest
    steps:
      - name: SQAaaS assessment step
        uses: eosc-synergy/sqaaas-assessment-action@v2

