name: SQAaaS IM

on:
  push:
    branches: ["sqa"]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:

  sqaaas_job:
    runs-on: ubuntu-latest
    steps:
      - name: Add tox unit test step definition for a SQAaaS assessment
        uses: eosc-synergy/sqaaas-step-action@v1
        id: tox_unit_test
        with:
#          name: tox_unit_test
#          tool: tox
#          tox_env: py3
          container: "python:3.12"
          tool: commands
          commands: pip install tox && tox -e py3

      - name: SQAaaS assessment step
        uses: eosc-synergy/sqaaas-assessment-action@v2
        with:
          qc_uni_steps: tox_unit_test
