name: Test IM

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  sqaaas_job:
    runs-on: ubuntu-latest
    name: Job that triggers SQAaaS platform
    steps:
      - name: SQAaaS action step
        uses: eosc-synergy/sqaaas-assessment-action@v1
