name: SQAaaS IM

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:

  sqaaas_job:
    runs-on: ubuntu-latest
    steps:
      - uses: eosc-synergy/sqaaas-assessment-action@v2

